export const LOAD_COLLABORATORS = 'LOAD_COLLABORATORS';
export const LOAD_COLLABORATORS_SUCCESS = 'LOAD_COLLABORATORS_SUCCESS';
export const LOAD_COLLABORATORS_FAILS = 'LOAD_COLLABORATORS_FAILS';

export const REMOVE_COLLABORATOR = 'REMOVE_COLLABORATOR';
